config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
 
  resources :items do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :areas

  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationRecord
  validates :area_text, presence: true
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  

   #空の投稿を保存できないようにする
   validates :prefecture_id, presence: true

   #ジャンルの選択が「---」の時は保存できないようにする
   validates :prefecture_id, numericality: { other_than: 0 } 

   belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :message, presence: true
  belongs_to :item  # itemテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション

end

app/models/item.rb
class Item < ApplicationRecord
  validates :text, presence: true
  has_one_attached :image
  belongs_to :user

  has_many :comments  # commentsテーブルとのアソシエーション

  def self.search(search)  #検索機能
    if search != ""
      Item.where('text LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 0, name: '---'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]

  include ActiveHash::Associations
  has_many :areas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :areas

  has_many :comments  # commentsテーブルとのアソシエーション
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday])
  end


end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  def index
    @areas = Area.all
  end

  def new
    @area = Area.new
  end

  def create
    Area.create(area_params)
    redirect_to '/'
  end

  def  destroy
    @area = Area.find(params[:id])
    @area.destroy
    redirect_to items_path # あとでareaに変更
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update  #更新
    area = Area.find(params[:id])
    area.update(area_params)
    redirect_to root_path   #pathはあとで確認して
  end

  def show
    @area = Area.find(params[:id])
  end

  private
  
  def area_params
    params.require(:area).permit(:area_text, :prefecture_id, :image).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/items/#{comment.item.id}" 
  end

  private
  def comment_params
    params.require(:comment).permit(:message).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  
  end

  def new
    @item = Item.new
  end

  def create  #保存
    Item.create(item_params)
    redirect_to '/'
  end

  def  destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def edit  #編集
    @item = Item.find(params[:id])
  end

  def update  #更新
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to root_path
  end

  def show   #詳細
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def search  #検索
    @items = Item.search(params[:keyword])
  end

  private


  def item_params
    params.require(:item).permit(:text, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @items = current_user.items
    @areas = current_user.areas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/areas/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @area, local: true) do |form| %>
      <%= form.file_field :image, id:"item-image" %>
      <%= form.text_area :area_text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/areas/index.html.erb
<div class="messages">
  <% @areas.each do |area| %>

  <div class="item-main">
    
  <div class="item"> 
   <%=area.user.nickname%> 

  <div class="item-date">
    <%= area.created_at %>
  </div> 

  <div class="item-content">
     <%= area.area_text %>
  </div>

  <% if area.image.attached? %>
    <%= image_tag area.image.variant(resize: '500x500'), class: 'message-image' if area.image.attached? %>
  <% end %>

<ul class="more_list">
  
     <%= link_to '詳細', area_path(area.id) %>
<%# <% if user_signed_in? && current_user.id == item.user_id %> 
     <%= link_to '編集', edit_area_path(area.id) %>
     <%= link_to '削除', area_path(area.id), data: { turbo_method: :delete } %>
<%# <% end %> 
<%# <a href="/users/<%= item.user.id %>
  </ul>
</div>
</div>

<hr class="hr1">

<% end %>

app/views/areas/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @area, local: true) do |form| %>
      <%= form.file_field :image, id:"area-image" %>  
      <%= form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      <%= form.text_area :area_text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/areas/show.html.erb
<div class="area">
  <% if @area.image.attached? %>
    <%= image_tag @area.image.variant(resize: '500x500'), class: 'message-image' %>
  <% end %>

  <div class="area-date">
    <%= @area.created_at %>
  </div>

  <div class="area-content">
    <%= @area.area_text %>
  </div>

  <ul class="more_list">
    <li>
      <%= link_to '編集', edit_area_path(@area) %>
    </li>
    <li>
      <%= link_to '削除', area_path(@area), data: { turbo_method: :delete } %>
    </li>

    <%# <span class="name">
      <a href="/users/<%= @item.user.id %>
        <%# <span>投稿者</span><%= @item.user.nickname %>
      <%# </a> %> 
    <%# </span> %> 
  </ul>
</div>

app/views/items/_main_chat.html.erb
<div class="chat-header">

  <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
    <a class="post bordered-button" href="/users/sign_in">ログイン</a>
    <a class="post bordered-button" href="/users/sign_up">新規登録</a>
  <% end %>

</div>


<div class="messages">
  <% @items.each do |item| %>

  <div class="item-main">
    
  <div class="item"> 
   <%=item.user.nickname%> 

  <div class="item-date">
    <%= item.created_at %>
  </div> 

  <div class="item-content">
     <%= item.text %>
  </div>

  <% if item.image.attached? %>
    <%= image_tag item.image.variant(resize: '500x500'), class: 'message-image' if item.image.attached? %>
  <% end %>

<ul class="more_list">
  
     <%= link_to '詳細', item_path(item.id) %>
<%# <% if user_signed_in? && current_user.id == item.user_id %> 
     <%= link_to '編集', edit_item_path(item.id) %>
     <%= link_to '削除', item_path(item.id), data: { turbo_method: :delete } %>
<%# <% end %> 
<%# <a href="/users/<%= item.user.id %>
  </ul>
</div>
</div>

<hr class="hr1">

<% end %>



 
  
</div>

app/views/items/_side_bar.html.erb
<div class="side-bar">
 <div class="side-header">
  <h1 class="grid-6"><a href="/">ぴよピヨ</a></h1>
  <%=image_tag('piyo.jpg', size: '100x100')%> 
 </div>

  <div class="toukou">
   <%=image_tag('pen.jpg', size: '50x50')%> 
    <div><%= link_to "投稿する", new_item_path, class: "post" %></div>
  </div>

 <div class="side-footer">
   <%=image_tag('kuma.jpg', size: '40x40')%> 
  <div><%= link_to 'エリアチャット', areas_path,class: "chat-area"%></div>
 </div>
 
</div>

app/views/items/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @item, local: true) do |form| %>
      <%= form.file_field :image, id:"item-image" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
  <div class='wrapper'>
    <div class='side-bar'>
      <%= render "side_bar" %>
    </div>

    <div class="chat">
     <%= render "main_chat" %>
    </div>
  </div>

          

app/views/items/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @item, local: true) do |form| %>
      <%= form.file_field :image, id:"item-image" %>  
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="messages">
  <% @items.each do |item| %>

  <div class="item-main">
    
  <div class="item"> 
   <%=item.user.nickname%> 

  <div class="item-date">
    <%= item.created_at %>
  </div> 

  <div class="item-content">
     <%= item.text %>
  </div>

  <% if item.image.attached? %>
    <%= image_tag item.image.variant(resize: '500x500'), class: 'message-image' if item.image.attached? %>
  <% end %>

<ul class="more_list">
  
     <%= link_to '詳細', item_path(item.id) %>
<%# <% if user_signed_in? && current_user.id == item.user_id %> 
     <%= link_to '編集', edit_item_path(item.id) %>
     <%= link_to '削除', item_path(item.id), data: { turbo_method: :delete } %>
<%# <% end %> 
<%# <a href="/users/<%= item.user.id %>
  </ul>
</div>
</div>

<hr class="hr1">

<% end %>

app/views/items/show.html.erb
<div class="item">
  <% if @item.image.attached? %>
    <%= image_tag @item.image.variant(resize: '500x500'), class: 'message-image' %>
  <% end %>

  <div class="item-date">
    <%= @item.created_at %>
  </div>

  <div class="item-content">
    <%= @item.text %>
  </div>

  <ul class="more_list">
    <li>
      <%= link_to '編集', edit_item_path(@item) %>
    </li>
    <li>
      <%= link_to '削除', item_path(@item), data: { turbo_method: :delete } %>
    </li>

    <%# <span class="name">
      <a href="/users/<%= @item.user.id %>
        <%# <span>投稿者</span><%= @item.user.nickname %>
      <%# </a> %> 
    <%# </span> %> 

  </ul>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@item, @comment], local: true) do |form| %>
        <%= form.text_area :message, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>

    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.message %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piyoniko</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

 

    <%= yield %>

    

  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @items.each do |item| %>
    <div class="content_post" style="background-image: url(<%= item.image %>);">
      <p><%= item.text %></p>
      <span class="name"><%= item.user.nickname %></span>
    </div>
  <% end %>
</div>


<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @areas.each do |area| %>
    <div class="content_post" style="background-image: url(<%= area.image %>);">
      <p><%= area.area_text %></p>
      <span class="name"><%= area.user.nickname %></span>
    </div>
  <% end %>
</div>